apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-postgres-pvc
  namespace: webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Smaller size for minikube
  storageClassName: standard  # Minikube's default storage class