apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
  namespace: webapp
type: Opaque
data:
  # Generate these with: echo -n 'your-value' | base64
  SECRET_KEY: bWluaWt1YmUtZGV2ZWxvcG1lbnQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # minikube-development-key-change-in-production
  DB_USER: cG9zdGdyZXM=      # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres