# Generated by Django 5.0.1 on 2024-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='rate_cycle',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
