# Generated by Django 5.0.4 on 2024-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0003_alter_payslip_deduction_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
