# Generated by Django 5.0.4 on 2024-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0006_alter_payslip_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(default='0'),
        ),
    ]
