# Generated by Django 5.0.4 on 2024-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0007_alter_employee_allowance_alter_employee_overtime_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(max_length=2),
        ),
    ]
