# Generated by Django 5.0.1 on 2024-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0002_rename_rate_cycle_payslip_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='deduction_health',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deduction_tax',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='earnings_allowance',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(default='100'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_cycle',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='rate',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_pay',
            field=models.FloatField(default='0'),
        ),
    ]
