# Generated by Django 5.0.4 on 2024-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0004_alter_payslip_date_range_alter_payslip_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
