# Generated by Django 5.0.4 on 2024-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0005_alter_payslip_date_range_alter_payslip_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(max_length=2),
        ),
    ]
