# Generated by Django 5.0.4 on 2024-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0008_payslip_gross_pay_alter_payslip_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ot_hrs',
            field=models.FloatField(null=True),
        ),
    ]
