# Generated by Django 5.0.4 on 2024-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lazapee', '0009_employee_ot_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_deduction',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ot_hrs',
            field=models.FloatField(default='0', null=True),
        ),
    ]
